version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - ./acme.json:/acme.json
    networks:
      - traefik
  
  web:
    image: ujstor/portfolio-web-go:1.0.2
    ports:
      - '${PORT_WEB}:${PORT_WEB}'
    networks:
      - traefik
    depends_on:
      - traefik
  
  notes:
    image: ujstor/flask-notes:1.0.0
    ports:
      - "${PORT_NOTES}:${PORT_NOTES}"
    networks:
      - traefik
    depends_on:
      - traefik 
  
  todo:
    image: ujstor/todo-go:1.0.0
    ports:
      - "${PORT_TODO}:${PORT_TODO}"
    depends_on:
      - psql
      - traefik
    networks:
      - traefik
  
  psql:
    image: postgres:latest
    build:
      context: .
      dockerfile: ./internal/database/initdb/Dockerfile.db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume_todo:/var/lib/postgresql/data
      - ./internal/database/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - traefik
    depends_on:
      - traefik

volumes:
  psql_volume_todo:

networks:
  traefik:
    external: true
